#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/bspwm/scripts/set_xrandr_display.sh
~/.config/bspwm/scripts/set_random_wallpaper.sh

~/.config/bspwm/scripts/launch_ui.sh
# ~/.config/bspwm/scripts/launch_compositor.sh


#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DP1 -d 1 2 3
bspc monitor DP2 -d 4 5 6
bspc monitor HDMI1 -d 7 8 9 10

bspc config border_width 5

bspc config focused_border_color \#98971a
bspc config normal_border_color \#504945

bspc config urgent_border_color \#B58900
bspc config presel_border_color \#26E2FF

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer true 
bspc config pointer_follows_focus true 

bspc config window_gap 0 

bspc config split_ratio 0.52

bspc config pointer_motion_interval 100 

# killall mpv -q
# bspc rule -a mpv desktop='^2' state=fullscreen --one-shot layer=below locked=on
# mpv 月詠み『生きるよすが』Music\ Video-86IxCGKUOzY.mkv --fs --loop --no-osc 
# mpv Live\ Wallpaper\ 4K\ Wonderful\ Landscape-m4P9XkF9gsI.mkv -fs --loop --no-osc & 

# killall kitty
# bspc rule -a kitty desktop='^2' state=fullscreen --one-shot layer=below locked=on
# kitty -e cmatrix & 
# bspc rule -a kitty desktop='^1' state=fullscreen --one-shot layer=below locked=on
# kitty -e tty-clock -s -c -t -n & 

#bspc rule -a kitty desktop='^2' state=fullscreen --one-shot layer=below locked=on
#kitty -e tty-clock -s -c -t -n & 
#bspc rule -a kitty desktop='^3' state=fullscreen --one-shot layer=below locked=on
#kitty -e tty-clock -s -c -t -n & 
